# -*- coding: utf-8 -*-
"""Rastreio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTTPaymzu1Xws5MoFs1QgfkeYF_5_5i3

#Importando o ultralytics, crew ai e configurando chave de APi
"""

!pip install -q ultralytics

!pip install crewai litellm --quiet

import os
os.environ["GEMINI_API_KEY"] = "GEMINI_API_KEY"

"""#Importando as bibliotecas, configurando e iniciando o rastreamento"""

import cv2
import json
from ultralytics import solutions

# Abrir vídeo
#https://pixabay.com/pt/videos/pessoas-com%C3%A9rcio-fazer-compras-6387/
cap = cv2.VideoCapture("videorastreio2.mp4")
assert cap.isOpened(), "Erro ao abrir vídeo"

w, h, fps = (int(cap.get(x)) for x in (
    cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

line_points = [(880, 400), (1080, 400)]  # Linha para contagem

# Criar objeto contador
counter = solutions.ObjectCounter(model="yolov8n.pt", classes=[0])
counter.region = line_points  # Definir região de contagem

video_writer = cv2.VideoWriter(
    "counting-output.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps, (w, h)
)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = counter.process(frame)

    # Salvar frame anotado no vídeo
    video_writer.write(results.plot_im)

    # Exibir contagens na tela (opcional)
    print(f"In count: {counter.in_count}, Out count: {counter.out_count}")

cap.release()
video_writer.release()

# Preparar dados para salvar em arquivo texto JSON
output_data = {
    "in_count": counter.in_count,
    "out_count": counter.out_count,
    "classwise_count": counter.classwise_count,
    "total_tracks": results.total_tracks
}

# Salvar dados em arquivo .txt (formato JSON legível)
with open("counting_output.txt", "w") as f:
    json.dump(output_data, f, indent=4)

print("Dados salvos em counting_output.txt")

import os
from crewai import LLM, Agent, Task, Crew

# Caminho do TXT
caminho_txt = "/content/counting_output.txt"

# Lendo o conteúdo do TXT
with open(caminho_txt, "r", encoding="utf-8") as f:
    conteudo_txt = f.read()

# Criando o LLM do Gemini
gemini_llm = LLM(
    model="gemini/gemini-2.0-flash",  # ou gemini-1.5-pro
    temperature=0.7,
    api_key=os.environ["GEMINI_API_KEY"]
)

# Criando um agente de exemplo
agent = Agent(
    role="Analista",
    goal="Gerar relatórios interpretativos a partir de dados de contagem de pessoas.",
    backstory="Especialista em análise de vídeo monitoramento e comportamento humano.",
    verbose=True,
    llm=gemini_llm
)

# Criando uma tarefa de exemplo
task = Task(
    description="Depois de uma analise de rastreamento gerou os dados de que 3 pessoas ultrapassaram uma area delimitada e 1 pessoa saiu, foram registradas com precisão 31 pessoas e quero que gere um relatório descritivo, claro e objetivo com os dados de rastreamento que estão no arquivo.",
    expected_output="Relatório textual interpretativo.",
    agent=agent,
    input=conteudo_txt
)

# Executando
crew = Crew(agents=[agent], tasks=[task], verbose=True)
resultado = crew.kickoff()
print(resultado)

